#!/usr/bin/env python3
"""从 Jekyll 的 _posts 提取博客元信息、摘要和章节结构。

产出 assets/content.js，供终端渲染文章列表，也作为 LLM 知识库的一部分——
只有标题的话，AI 回答"这篇文章讲了什么"时只能瞎猜。
"""
import re, json, pathlib

HERE  = pathlib.Path(__file__).resolve().parent.parent
POSTS = HERE.parent / "_posts"
OUT   = HERE / "assets" / "content.js"

EXCERPT_CHARS = 260
MAX_HEADINGS  = 12


def front_matter(text):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return {}, text
    meta, body = {}, text[m.end():]
    key = None
    for line in m.group(1).splitlines():
        if re.match(r"^\s*-\s+", line) and key:
            meta.setdefault(key, []).append(line.split("-", 1)[1].strip().strip("'\""))
        elif ":" in line:
            k, v = line.split(":", 1)
            key = k.strip()
            v = v.strip().strip("'\"")
            if v:
                meta[key] = v
    return meta, body


def clean(md):
    """把 markdown 正文压成给模型读的纯文本。"""
    md = re.sub(r"```.*?```", " ", md, flags=re.S)          # 代码块
    md = re.sub(r"<[^>]+>", " ", md)                        # 内联 HTML
    md = re.sub(r"\$\$.*?\$\$", " ", md, flags=re.S)        # 块级公式
    md = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", md)           # 图片
    md = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", md)        # 链接留文字
    md = re.sub(r"[#*`>_|-]+", " ", md)
    md = re.sub(r"\{[%{].*?[%}]\}", " ", md)                # liquid 标签
    return re.sub(r"\s+", " ", md).strip()


def build():
    out = []
    for f in sorted(POSTS.glob("*.md"), reverse=True):
        text = f.read_text(encoding="utf-8", errors="ignore")
        meta, body = front_matter(text)
        if str(meta.get("published", "")).lower() == "false":
            continue

        date = meta.get("date") or f.name[:10]
        title = meta.get("title")
        if not title:                                       # 没有 front matter 的文件
            h = re.search(r"^#\s+(.+)$", body, re.M)
            title = h.group(1).strip() if h else f.stem

        permalink = meta.get("permalink", "")
        slug = permalink.strip("/").split("/")[-1] if permalink else \
               re.sub(r"^\d{4}-\d{2}-\d{2}-", "", f.stem)

        tags = meta.get("tags") or meta.get("tag") or []
        if isinstance(tags, str):
            tags = [t.strip() for t in tags.split(",") if t.strip()]

        headings = [h.strip() for h in re.findall(r"^#{2,3}\s+(.+)$", body, re.M)]
        headings = [re.sub(r"[#*`]", "", h) for h in headings][:MAX_HEADINGS]

        entry = {
            "slug": slug,
            "date": str(date)[:10],
            "title": title,
            "tags": tags,
            "url": permalink or None,
            "excerpt": clean(body)[:EXCERPT_CHARS],
            "headings": headings,
        }
        if not meta:
            entry["warn"] = "缺 front matter"
        out.append({k: v for k, v in entry.items() if v})

    out.sort(key=lambda p: p["date"], reverse=True)
    OUT.write_text(
        "/* generated by tools/extract_posts.py — do not edit by hand */\n"
        "window.POSTS_DATA = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")

    print(f"{len(out)} published posts -> {OUT.name}  ({OUT.stat().st_size/1024:.1f}KB)\n")
    for p in out:
        print(f"  {p['date']}  {p['title'][:52]:<54} {len(p.get('headings', []))} sections")


if __name__ == "__main__":
    build()
