#!/usr/bin/env python3
"""把一张人像照片编译成像素画数据，供终端主页在前端重绘。

产出 assets/avatar.js，内含：
  luma  — 逐像素亮度（16 级，1 hex char/px），前端按主题渐变着色
  pal   — 自适应 16 色调色板
  idx   — 逐像素调色板索引（1 hex char/px）

换照片时改 SRC 和 CROP 后重跑即可。
"""
from PIL import Image, ImageEnhance, ImageFilter, ImageOps
import json, pathlib

HERE = pathlib.Path(__file__).resolve().parent.parent
SRC  = HERE / "tools" / "source.jpg"
OUT  = HERE / "assets" / "avatar.js"

NW, NH = 108, 144    # 输出网格，3:4 竖版，容得下头肩
CROP   = (0, 18, 413, 569)   # 裁剪框 left, top, right, bottom（同为 3:4）
COLORS = 16

def build():
    im = Image.open(SRC).convert("RGB").crop(CROP)

    # 先在高分辨率上锐化，降采样后五官才立得住
    im = im.resize((NW * 5, NH * 5), Image.LANCZOS)
    im = im.filter(ImageFilter.UnsharpMask(radius=5, percent=150, threshold=2))
    im = im.resize((NW, NH), Image.LANCZOS)

    im = ImageEnhance.Contrast(im).enhance(1.22)
    im = ImageEnhance.Color(im).enhance(1.10)

    # --- 亮度层：拉满动态范围后量化到 16 级 ---
    g = ImageOps.autocontrast(im.convert("L"), cutoff=1)
    luma = "".join(f"{p * 16 // 256:x}" for p in g.tobytes())

    # --- 彩色层：自适应 16 色 ---
    q = im.quantize(colors=COLORS, method=Image.MEDIANCUT, dither=Image.FLOYDSTEINBERG)
    raw = q.getpalette()[: COLORS * 3]
    pal = ["#%02x%02x%02x" % tuple(raw[i * 3:i * 3 + 3]) for i in range(COLORS)]
    idx = "".join(f"{p:x}" for p in q.tobytes())

    OUT.write_text(
        "/* generated by tools/pixelize.py — do not edit by hand */\n"
        "window.AVATAR_DATA = " + json.dumps(
            {"w": NW, "h": NH, "luma": luma, "pal": pal, "idx": idx}, separators=(",", ":")) + ";\n",
        encoding="utf-8")

    # 终端预览，确认还认得出人
    ramp = "@%#*+=-:. "
    print(f"crop={CROP}  ->  {NW}x{NH}, {COLORS} colors, {OUT.stat().st_size/1024:.1f}KB\n")
    sx = max(1, NW // 46)
    for y in range(0, NH, sx * 2):
        print("".join(ramp[int(luma[y * NW + x], 16) * 10 // 16] for x in range(0, NW, sx)))

if __name__ == "__main__":
    build()
